LeGenieDePetra\mainBundle\Entity\dette:
    type: entity
    table: null
    repositoryClass: LeGenieDePetra\mainBundle\Repository\detteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        somme:
            type: integer
        preteur:
            type: string
            length: 255
        date:
            type: date
    lifecycleCallbacks: {  }
