<?php

namespace LeGenieDePetra\mainBundle\Repository;

/**
 * detteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class detteRepository extends \Doctrine\ORM\EntityRepository
{
}
