<?php

namespace LeGenieDePetra\mainBundle\Repository;

/**
 * pretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pretRepository extends \Doctrine\ORM\EntityRepository
{
}
